package silentorb.mythic.editing

object EditorCommands {
  val addNode = "addNode"
  val addNodeWithNameDialog = "addNodeWithNameDialog"
  val renameNode = "renameNode"
  val renameNodeWithNameDialog = "renameNodeWithNameDialog"
  val deleteNode = "deleteNode"
  val copyNode = "copyNode"
  val pasteNode = "pasteNode"
  val duplicateNode = "duplicateNode"
  val startNodeSelect = "startNodeSelect"
  val startNodeDrillDown = "startNodeDrillDown"
  val trySelectJoint = "trySelectJoint"
  val selectJoint = "selectJoint"
  val connectJoints = "connectJoints"

  val setGraphValue = "setGraphValue"
  val replaceGraphValue = "replaceGraphValue"
  val removeGraphValue = "removeGraphValue"
  val setActiveGraph = "setActiveGraph"
  val setNodeSelection = "setNodeSelection"
  val setFileSelection = "setFileSelection"
  val setViewportBounds = "setViewportBounds"

  val startTranslating = "startTranslating"
  val startRotating = "startRotating"
  val startScaling = "startScaling"
  val restrictAxisX = "restrictAxisX"
  val restrictAxisY = "restrictAxisY"
  val restrictAxisZ = "restrictAxisZ"
  val commitOperation = "commitOperation"
  val cancelOperation = "cancelOperation"

  val zoomIn = "zoomIn"
  val zoomOut = "zoomOut"

  val viewTop = "viewTop"
  val viewFront = "viewFront"
  val viewBack = "viewBack"
  val viewLeft = "viewLeft"
  val viewRight = "viewRight"
  val viewBottom = "viewBottom"
  val toggleProjectionMode = "toggleProjectionMode"
  val centerOnSelection = "centerOnSelection"
  val renderingModeWireframe = "renderingModeWireframe"
  val renderingModeFlat = "renderingModeFlat"
  val renderingModeLit = "renderingModeLit"
  val toggleFlythroughMode = "toggleFlythroughMode"
  val startConnecting = "startConnecting"

  val newFile = "newFile"
  val duplicateFile = "duplicateFile"
  val newFileWithNameDialog = "newFileWithNameDialog"
  val newFolder = "newFolder"
  val newFolderWithNameDialog = "newFolderWithNameDialog"
  val moveFileItem = "moveFileItem"
  val deleteFileItem = "deleteFileItem"
  val renameFileItemWithNameDialog = "renameFileItemWithNameDialog"

  val undo = "undo"
  val redo = "redo"

  val playGame = "playGame"
  val playScene = "playScene"
}
